volumes:
  mqtt_data:
  mqtt_log:

services:
  mosquitto:
    container_name: "eclipse-mosquitto"
    restart: "unless-stopped"
    environment:
      - "TZ=EST5EDT"
      - DEFAULT_USERNAME=$DEFAULT_MQTT_USERNAME
      - DEFAULT_PASSWORD=$DEFAULT_MQTT_PASSWORD
    hostname: "mqtt"
    build: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "mqtt_data:/mosquitto/data"
      - "mqtt_log:/mosquitto/log"
